linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis checks
    - typecheck     # Type-check Go code
    - unused        # Check for unused constants, variables, functions
    - gofmt         # Check if code is gofmt-ed
    - goimports     # Check import formatting
    - misspell      # Find commonly misspelled words
    - lll           # Line length limit (120 chars)
    - gocritic      # Provides diagnostics that check for bugs
    - revive        # Replacement for golint
    - gocyclo       # Computes cyclomatic complexity
    - gosec         # Security checker
    - deadcode      # Find unused code
    - varcheck      # Find unused global variables and constants

  disable:
    - structcheck   # Often gives false positives

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec