
version: "3.0"

app_config:
  env: "DEV"
  mode: "debug"

server:
  host: "0.0.0.0"
  port: 8080

postgres:
  host: "localhost"
  port: 5455
  user: "postgres"
  password: "pgadmin"
  database: "go_dev"
